// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGthlMapping = "gthl_mappings"

// GthlMapping mapped from table <gthl_mappings>
type GthlMapping struct {
	Location  string `gorm:"column:location;primaryKey" json:"location"`
	SurfaceID int32  `gorm:"column:surface_id;not null" json:"surface_id"`
}

// TableName GthlMapping's table name
func (*GthlMapping) TableName() string {
	return TableNameGthlMapping
}
