// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMhlMapping = "mhl_mappings"

// MhlMapping mapped from table <mhl_mappings>
type MhlMapping struct {
	Location  string `gorm:"column:location;primaryKey" json:"location"`
	SurfaceID int32  `gorm:"column:surface_id;not null" json:"surface_id"`
}

// TableName MhlMapping's table name
func (*MhlMapping) TableName() string {
	return TableNameMhlMapping
}
