// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOhfTeam = "ohf_teams"

// OhfTeam mapped from table <ohf_teams>
type OhfTeam struct {
	TeamNumber             string `gorm:"column:team_number" json:"team_number"`
	TeamName               string `gorm:"column:team_name" json:"team_name"`
	TeamOrganization       string `gorm:"column:team_organization" json:"team_organization"`
	TeamOrganizationPath   string `gorm:"column:team_organization_path" json:"team_organization_path"`
	TeamGenderIdentity     string `gorm:"column:team_gender_identity" json:"team_gender_identity"`
	DivisionName           string `gorm:"column:division_name" json:"division_name"`
	RegistrationsClassName string `gorm:"column:registrations_class_name" json:"registrations_class_name"`
	CategoryName           string `gorm:"column:category_name" json:"category_name"`
}

// TableName OhfTeam's table name
func (*OhfTeam) TableName() string {
	return TableNameOhfTeam
}
