// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProvince = "provinces"

// Province mapped from table <provinces>
type Province struct {
	ID           int32  `gorm:"column:id;primaryKey" json:"id"`
	ProvinceName string `gorm:"column:province_name;not null" json:"province_name"`
	Country      string `gorm:"column:country;not null" json:"country"`
}

// TableName Province's table name
func (*Province) TableName() string {
	return TableNameProvince
}
