// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRendition = "renditions"

// Rendition mapped from table <renditions>
type Rendition struct {
	ID        int32  `gorm:"column:id;primaryKey" json:"id"`
	SurfaceID int32  `gorm:"column:surface_id;not null" json:"surface_id"`
	Name      string `gorm:"column:name;not null" json:"name"`
	Width     int32  `gorm:"column:width;not null" json:"width"`
	Height    int32  `gorm:"column:height;not null" json:"height"`
	Ratio     string `gorm:"column:ratio;not null" json:"ratio"`
	Bitrate   int64  `gorm:"column:bitrate;not null" json:"bitrate"`
}

// TableName Rendition's table name
func (*Rendition) TableName() string {
	return TableNameRendition
}
