// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSite = "sites"

// Site mapped from table <sites>
type Site struct {
	Site string `gorm:"column:site;primaryKey" json:"site"`
	URL  string `gorm:"column:url;not null" json:"url"`
}

// TableName Site's table name
func (*Site) TableName() string {
	return TableNameSite
}
