// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"time"
)

const TableNameSitesConfig = "sites_config"

// ParserConfig represents JSON data for parser_config field
type ParserConfig map[string]interface{}

// Scan implements sql.Scanner interface
func (pc *ParserConfig) Scan(value interface{}) error {
	if value == nil {
		*pc = nil
		return nil
	}
	bytes, ok := value.([]byte)
	if !ok {
		return nil
	}
	return json.Unmarshal(bytes, pc)
}

// Value implements driver.Valuer interface
func (pc ParserConfig) Value() (driver.Value, error) {
	if pc == nil {
		return nil, nil
	}
	return json.Marshal(pc)
}

// SitesConfig mapped from table <sites_config>
type SitesConfig struct {
	ID                   int32          `gorm:"column:id;primaryKey;autoIncrement" json:"id"`
	SiteName             string         `gorm:"column:site_name;not null;uniqueIndex" json:"site_name"`
	DisplayName          sql.NullString `gorm:"column:display_name" json:"display_name"`
	BaseURL              string         `gorm:"column:base_url;not null" json:"base_url"`
	HomeTeam             sql.NullString `gorm:"column:home_team" json:"home_team"`
	ParserType           string         `gorm:"column:parser_type;not null" json:"parser_type"`
	ParserConfig         *ParserConfig  `gorm:"column:parser_config;type:json" json:"parser_config"`
	Enabled              sql.NullBool   `gorm:"column:enabled;default:1" json:"enabled"`
	LastScrapedAt        sql.NullTime   `gorm:"column:last_scraped_at" json:"last_scraped_at"`
	ScrapeFrequencyHours sql.NullInt32  `gorm:"column:scrape_frequency_hours;default:24" json:"scrape_frequency_hours"`
	Notes                sql.NullString `gorm:"column:notes" json:"notes"`
	CreatedAt            time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt            time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName SitesConfig's table name
func (*SitesConfig) TableName() string {
	return TableNameSitesConfig
}

// MarshalJSON implements json.Marshaler interface
func (sc SitesConfig) MarshalJSON() ([]byte, error) {
	type Alias SitesConfig
	return json.Marshal(&struct {
		DisplayName          string  `json:"display_name"`
		HomeTeam             string  `json:"home_team"`
		Enabled              *bool   `json:"enabled"`
		LastScrapedAt        *time.Time `json:"last_scraped_at"`
		ScrapeFrequencyHours *int32  `json:"scrape_frequency_hours"`
		Notes                string  `json:"notes"`
		*Alias
	}{
		DisplayName:          nullStringToString(sc.DisplayName),
		HomeTeam:             nullStringToString(sc.HomeTeam),
		Enabled:              nullBoolToPtr(sc.Enabled),
		LastScrapedAt:        nullTimeToPtr(sc.LastScrapedAt),
		ScrapeFrequencyHours: nullInt32ToPtr(sc.ScrapeFrequencyHours),
		Notes:                nullStringToString(sc.Notes),
		Alias:                (*Alias)(&sc),
	})
}

func nullStringToString(ns sql.NullString) string {
	if ns.Valid {
		return ns.String
	}
	return ""
}

func nullBoolToPtr(nb sql.NullBool) *bool {
	if nb.Valid {
		return &nb.Bool
	}
	return nil
}

func nullTimeToPtr(nt sql.NullTime) *time.Time {
	if nt.Valid {
		return &nt.Time
	}
	return nil
}

func nullInt32ToPtr(ni sql.NullInt32) *int32 {
	if ni.Valid {
		return &ni.Int32
	}
	return nil
}
