// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSitesLocation = "sites_locations"

// SitesLocation mapped from table <sites_locations>
type SitesLocation struct {
	Site       string `gorm:"column:site;not null" json:"site"`
	Location   string `gorm:"column:location" json:"location"`
	LocationID int32  `gorm:"column:location_id" json:"location_id"`
	Loc        string `gorm:"column:loc" json:"loc"`
	Surface    string `gorm:"column:surface" json:"surface"`
	Address    string `gorm:"column:address" json:"address"`
	MatchType  string `gorm:"column:match_type" json:"match_type"`
	SurfaceID  int32  `gorm:"column:surface_id;not null" json:"surface_id"`
}

// TableName SitesLocation's table name
func (*SitesLocation) TableName() string {
	return TableNameSitesLocation
}
