// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSurfaceFeedMode = "surface_feed_modes"

// SurfaceFeedMode mapped from table <surface_feed_modes>
type SurfaceFeedMode struct {
	SurfaceID  int32 `gorm:"column:surface_id;primaryKey" json:"surface_id"`
	FeedModeID int32 `gorm:"column:feed_mode_id;primaryKey" json:"feed_mode_id"`
}

// TableName SurfaceFeedMode's table name
func (*SurfaceFeedMode) TableName() string {
	return TableNameSurfaceFeedMode
}
