// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTodbSurface = "todb_surfaces"

// TodbSurface mapped from table <todb_surfaces>
type TodbSurface struct {
	ID            int32  `gorm:"column:id;primaryKey" json:"id"`
	Fullname      string `gorm:"column:fullname" json:"fullname"`
	Fullshortname string `gorm:"column:fullshortname" json:"fullshortname"`
	Street        string `gorm:"column:street" json:"street"`
	City          string `gorm:"column:city" json:"city"`
	Province      string `gorm:"column:province" json:"province"`
}

// TableName TodbSurface's table name
func (*TodbSurface) TableName() string {
	return TableNameTodbSurface
}
